version: "3.8"

services:
  mongo:
    image: mongo:8
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: AuthDb

volumes:
  mongo-data:
